In [ ]:
AI Types
==========
Narrow AI - Chatbot,Google Assistant
General AI - 
Super AI -
    
AI Functionality
================
Reactive Machines - Responds to input without memory   Ex: Chess-playing 
Limited Memory  -  Learn from past data to imporve    Ex: self driving cars
Theory of Mind - Understand emotions and social interactions


1. Collect the data 
2. Train Model
3. Test Model
4. Deploy
5. Improve 
==============================================================
Data 
-----
 |->Text Audio Video Image or any unstructured data ...

DataAnalysis
==============
1. Collect the data -->2. Process Data  -------> 3. EDA  4. Visualization  ===> Model(MachineLearning)
                       |->clean up                              
                           |->omit duplicate values
                           |->replace empty values
                           |->drop unwanted columns
                           |->drop outliers 
numpy
pandas 
matplotlib 

MachineLearning(ML)
====================
General Program:
---------------
Programmer:   Input ---->[M/C]-->output
Vs
ML programming: Input and Output --->[M/C] -->Algorithm(model)

1. Collect Data  <== from DataAnalysis 
2. Prepare
3. Select the model 
4. Train the model
5. Test 
6. Deploy 
7. Monitor 

Supervised Learning
|->labeled data(input + correct answer)
Liner Regression,Decision Tree,...

Unsupervised Learning
|->no label 

Reinforcement Learning
|->trial and error (ex: sef-driving cars)
Graph Machine Learning (GML)
-----------------------------
  |-> Graph       (pA)--------(pB)
       G=(V,E)                 |
                      (pC) ----|
----------------------------------------------------------

Deep Learning Works
----------------------
1. Collect the data (ex: images,sounds,audios,...)
2. Neual Network 
3. Hidden layers (processing) ...
4. Output layers 

ANN
CNN 
RNN(Recurrent Neual Network) Language Transalation , Speech recognition 
|
Transformer Network  -> NLP,Summarization...
====================================================================================
GenerativeAI (Gen AI)
    |
    Create new content(text,image,video,audio..)
    LLM ( Text )
                       
Gen AI LLM - Text - ChatGPT
           - Image - DALL-E


EndUser: Get list of sales emp's records ? (user input)
         -------------------------------
                    |                |
                    LLM <== pre-trainined ML,DL models 
                    |  
                    VectorDataBase(oracle23 ai,FAISS,Chroma,..)
                    ---------------// select *from emp where edept = sales //SQL
                                        |
Gen AI => Learn from existing data to create new,original content//
-------
LLM ==> predict the next word in sentence, given all the previous words
---
===========================================================================
Agentic AI - AI Agents
                 |->think,plan,take action,use tools 

Query: travel date -> to delhi  
ChatGPT -> .......... travel modes ..
                       Vs
Query: travel date -> to delhi  
      ....    .... visiting places + hotels + ....                        

In [ ]:
NLP
----
1. Text preprocessing
   - Tokenization
   - lemmatization
   - stop words
2. Text processing
   - Bagofwords
   - ngram
   - TF-IDF 
3. Text processing
    - word2vector 
    - Deeplearning techniques 
       ()  () ()
4.  transformer 
5. BERT 
-----------------------------
2002 -> Supermarket Billing (VB,MSAccess) => Desktop Application
         ====================
2025 -> ..... pre-trained model + records = own RAG ->chatbot 

In [ ]:
Python
=======
 |-> 1. procedure style code = direct approach ->  var = 10 <== direct initialization
                                                   def fx():
                                                        ..
                                                   fx() <== direct call

 |-> 2. object oriented style code => class<-->object
                                                    obj1.var = 10 <== object based initialization
                                                    obj2.var = 10 <== object based initialization
                                                    obj1.fx() <== methodCall

 |-> 3. Functional style code => Expression (or) SinglelineCode - computing/analysis..

In [ ]:
In python everything is an object
         --------------------------
number - int,float,complex
a-zA-Z0-9specialchars - str 
int float complex str bytes bool NoneType 
list [ ]
tuple ( )
dict {key:Value,key1:value,Key2:value...}
set 
------------------------------------//

In [ ]:
fname='emp.csv'
findx=123
fsize='5KB'
futil = 98.54
fstatus = True

fileInfo1 = ['emp.csv',123,'5KB',98.54,True] <== list

fileInfo2 = ('emp.csv',123,'5KB',98.54,True) <== tuple

fileInfo3 = {'K1':'emp.csv','K2':123,'K3':'5KB','K4':98.54,'K5':True} <== dict

class classname:
    attribute 

python user defined class - mutable - using classname - we can add new attribute
                                                        we can modify an existing attribute
                                                        we can delete an existing attribute
- template (or) blue print of an object

In [2]:
class fileInfo:
    fname=''
    findex=0
print(fileInfo)

<class '__main__.fileInfo'>


In [3]:
print(fileInfo())

In [4]:
obj1 = fileInfo()
obj2 = fileInfo()

In [5]:
print(type(obj1),type(obj2))

<class '__main__.fileInfo'> <class '__main__.fileInfo'>


In [6]:
print(type(10),type(20))

<class 'int'> <class 'int'>


In [7]:
obj1

In [8]:
obj2

In [ ]:
 +------------+
 | [] (white) |   <== blueprint/sheet  -- Class
 +------------+
  |           |_________
+------------+         +------------+
| [] (white) |         | [] (white) |
+------------+         +------------+
  1st main                 2nd main

In [9]:
class fileInfo:
    fname=''
    findex=0

obj1 = fileInfo()
obj1.fname = "emp.csv"
obj1.findex = 101

obj2 = fileInfo()
obj2.fname = "prod.log"
obj2.findex = 102
print(obj1.fname,obj1.findex)

emp.csv 101


In [10]:
print(obj2.fname,obj2.findex)

prod.log 102


In [11]:
L=[]

def f1(a):
    return a+100

for var in [10,20,30,40,50]:
    r = f1(var)
    L.append(r)
    
print(L)

[110, 120, 130, 140, 150]


In [12]:
list(map(lambda a:a+100,[10,20,30,40,50]))

[110, 120, 130, 140, 150]

In [13]:
d={}
d['K1'] = list(map(lambda a:a+100,[10,20,30,40,50]))
d

{'K1': [110, 120, 130, 140, 150]}

In [ ]:
1. lambda
---------
lambda - python keyword - function call with args and return some value
lambda <list of args>:<basicOperation>
         .........      .........

In [14]:
def f1(a1,a2):
    return a1+a2

f1(10,20) # named function call with arguments

30

In [16]:
f2 = lambda a1,a2:a1+a2
f2(10,20) # unnamed function

30

In [17]:
# list comprehesion = list append operation
L=[]

for var in [10,20,30,40,50]:
    r = var+100
    L.append(r)
    
print(L)

[110, 120, 130, 140, 150]


In [18]:
[var+100 for var in [10,20,30,40,50]]

[110, 120, 130, 140, 150]

In [19]:
# Generator - function returns an address(iterator)
# ---------   -------- ========= yield ===========

def fA():
    return 10

def fB():
    yield 10

print(type(fA),type(fB))

<class 'function'> <class 'function'>


In [22]:
print(type(fA()))
print(type(fB()))

<class 'int'>
<class 'generator'>


In [23]:
fB()

<generator object fB at 0x0000029938D1F7F0>

In [ ]:
1. next(genObject) ... StopIteration
2. for loop => for var in genObj:
                      ..
3. type cast to list => list(genObj)

In [25]:
list(fB())

[10]

In [ ]:
map(function,collection) ->genObject
     |          |                |-->typecast to list() ; for loop
  lambda    comprehension/inputCollection

In [28]:
list(map(lambda a:a+100,[10,20,30,40,50]))

[110, 120, 130, 140, 150]

In [ ]:
####################################

In [ ]:
python.org
------------
 we can do general python program
 not ML DL llm DA..
pip install numpy
pip install pandas
...

anaconda.com/downloads 
 |->python + ML libs available
===============================

In [ ]:
# Tokenization
Tokenization is the process of breaking text into smaller pieces (token)
token - word / subwords/ characters
-----
 |->Convert to numbers (vector) =>for model understand 

Hello Good Morning          ..................
(English) ------------------>(French..)

hello  -> [101030]   
good   -> [101010]
morning -> [101033]

"I likes to read machine learning algorithm"
word-level => ["I", "likes", "to","read","machine","learning","algorithm"]
subword-leve =>["I", "likes", "to","read","machine", "learn","ing","algo","rithm"]

NLP terms
-----------
1. Corpus  - paragraph 
2. Documents - sentences
3. vocabulary - unique words present in the paragraph

nltk tool kit <== import nltk
download model 
apply word/sentence///

In [29]:
import nltk

In [30]:
text = "I likes to read machine learning algorithm"

from nltk.tokenize import word_tokenize
word_tokenize(text)

['I', 'likes', 'to', 'read', 'machine', 'learning', 'algorithm']

In [ ]:
LookupError
>>> import nltk
>>> nltk.download('punkt_tab')
import nltk
nltk.download('punkt_tab')

In [ ]:
import nltk
nltk.download('punkt_tab')

In [ ]:
"hello" # OK
"hello' # Error 
'''....
   .....'''
"""
 ....
 .... """

In [32]:
corpus = '''Hello welcome,to Gen AI NLP lecture
pleas do activity ! to become expect in NLP'''
word_tokenize(corpus)

['Hello',
 'welcome',
 ',',
 'to',
 'Gen',
 'AI',
 'NLP',
 'lecture',
 'pleas',
 'do',
 'activity',
 '!',
 'to',
 'become',
 'expect',
 'in',
 'NLP']

In [33]:
from nltk.tokenize import word_tokenize 
from nltk.tokenize import sent_tokenize
sent_tokenize(corpus)

['Hello welcome,to Gen AI NLP lecture\npleas do activity !',
 'to become expect in NLP']

In [34]:
msg="Hello arun,How are you doing ? OK. I am doing NLP activitites's code ab'c data1.data2 #!/bin"

In [35]:
word_tokenize(msg)

['Hello',
 'arun',
 ',',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'OK',
 '.',
 'I',
 'am',
 'doing',
 'NLP',
 'activitites',
 "'s",
 'code',
 'ab',
 "'",
 'c',
 'data1.data2',
 '#',
 '!',
 '/bin']

In [36]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(msg)

['Hello',
 'arun',
 ',',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'OK',
 '.',
 'I',
 'am',
 'doing',
 'NLP',
 'activitites',
 "'",
 's',
 'code',
 'ab',
 "'",
 'c',
 'data1',
 '.',
 'data2',
 '#!/',
 'bin']

In [37]:
from nltk.tokenize import TreebankWordTokenizer
print(TreebankWordTokenizer)

<class 'nltk.tokenize.treebank.TreebankWordTokenizer'>


In [38]:
nltk.__file__

'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\nltk\\__init__.py'

In [ ]:
<class 'nltk.tokenize.treebank.TreebankWordTokenizer'>
nltk/
  |__tokenize/
            |__treebank.py
                    |
                    |->class TreebankWordTokenizer:
                                 ...

In [40]:
msg="I can't do this, can i? ab'c def'g hi:j"
from nltk.tokenize import TreebankWordTokenizer
obj = TreebankWordTokenizer()
obj.tokenize(msg)

['I',
 'ca',
 "n't",
 'do',
 'this',
 ',',
 'can',
 'i',
 '?',
 "ab'c",
 "def'g",
 'hi',
 ':',
 'j']

In [41]:
text = "They'll test-drive the car tomorrow."

from nltk.tokenize import word_tokenize,TreebankWordTokenizer,WordPunctTokenizer

In [42]:
print(word_tokenize(text))

['They', "'ll", 'test-drive', 'the', 'car', 'tomorrow', '.']


In [43]:
print(TreebankWordTokenizer().tokenize(text))

['They', "'ll", 'test-drive', 'the', 'car', 'tomorrow', '.']


In [44]:
print(WordPunctTokenizer().tokenize(text))

['They', "'", 'll', 'test', '-', 'drive', 'the', 'car', 'tomorrow', '.']


In [45]:
## stemming - stem => reduce the root word 
from nltk.stem import PorterStemmer
obj_stemming = PorterStemmer()
obj_stemming.stem("eating")

'eat'

In [46]:
obj_stemming.stem("history")

'histori'

In [47]:
obj_stemming.stem("learning")

'learn'

In [48]:
obj_stemming.stem("congratulations")

'congratul'

In [49]:
#regex expression
from nltk.stem import RegexpStemmer
reg_stemm = RegexpStemmer("ing$|s$|e$")
reg_stemm.stem("eating")

'eat'

In [50]:
reg_stemm.stem("history")

'history'

In [51]:
reg_stemm.stem("abcd")

'abcd'

In [52]:
reg_stemm.stem("abcde")

'abcd'

In [53]:
# Lemmatization - lemma 
# reduce root word - based on pos='v' ''

from nltk.stem import WordNetLemmatizer
lemmatize_obj = WordNetLemmatizer()
lemmatize_obj.lemmatize("eating")

'eating'

In [54]:
lemmatize_obj.lemmatize("eating",pos='v')

'eat'

In [55]:
lemmatize_obj.lemmatize("history",pos='v')

'history'

In [57]:
#help(lemmatize_obj)

In [ ]:
the hotel food is good  => hotel food good => [123,442,552] ->DB ...

In [58]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [60]:
stopwords.words('english')
stopwords.words('french')

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton',
 'tu',
 'un',
 'une',
 'vos',
 'votre',
 'vous',
 'c',
 'd',
 'j',
 'l',
 'à',
 'm',
 'n',
 's',
 't',
 'y',
 'été',
 'étée',
 'étées',
 'étés',
 'étant',
 'étante',
 'étants',
 'étantes',
 'suis',
 'es',
 'est',
 'sommes',
 'êtes',
 'sont',
 'serai',
 'seras',
 'sera',
 'serons',
 'serez',
 'seront',
 'serais',
 'serait',
 'serions',
 'seriez',
 'seraient',
 'étais',
 'était',
 'étions',
 'étiez',
 'étaient',
 'fus',
 'fut',
 'fûmes',
 'fûtes',
 'furent',
 'sois',
 'soit',
 'soyons',
 'soyez',
 'soient',
 'fusse',
 'fusses',
 'fût',
 'fussions',
 'fussiez',
 'fussent',
 'ayant',
 'ayante',
 'ayantes',


In [61]:
# To get list stopwords from other language 
stopwords.fileids()

['albanian',
 'arabic',
 'azerbaijani',
 'basque',
 'belarusian',
 'bengali',
 'catalan',
 'chinese',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hebrew',
 'hinglish',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'tamil',
 'turkish']

In [62]:
stopwords.words('arabic')

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [ ]:
########## Lunch break.

In [ ]:
Given_list=["words","eats","eatern","writing","writes","programming","program","history","finally",
            "finalized"]

# import nltk module
# using PorterStemmer - omit given list - root words
# using WordNetLemmatizer - pos=v

In [63]:
Given_list=["words","eats","eatern","writing","writes","programming","program","history","finally",
            "finalized"]

stemming_obj = PorterStemmer()

for var in Given_list:
    print(f'{var} --> {stemming_obj.stem(var)}')

words --> word
eats --> eat
eatern --> eatern
writing --> write
writes --> write
programming --> program
program --> program
history --> histori
finally --> final
finalized --> final


In [64]:
lemmatizer_obj = WordNetLemmatizer()
for var in Given_list:
    print(f"{var} --> {lemmatizer_obj.lemmatize(var,pos='v')}")

words --> word
eats --> eat
eatern --> eatern
writing --> write
writes --> write
programming --> program
program --> program
history --> history
finally --> finally
finalized --> finalize


In [68]:
msg="This is an example displaying off list of or collection stop words filters"
# do wordtokenize
# ---------------
# stopwords.words('english')
# ----//filter non-stop words 
# display filter words
print(msg)

This is an example displaying off list of or collection stop words filters


In [67]:
words = word_tokenize(msg)
for var in words:
    if var.lower() not in stopwords.words('english'):
        print(var)

example
displaying
list
collection
stop
words
filters


In [70]:
words = word_tokenize(msg)
filterd_words = [var for var in words if var.lower() not in stopwords.words('english')]
filterd_words

['example', 'displaying', 'list', 'collection', 'stop', 'words', 'filters']

In [ ]:
Task
=====
Corpus

|->use PorterStemmer() and WordNetLemmatizer()
|->apply stopwords
|->filter remaning words 



In [71]:
corpus='''Dr.Sarabhai is considered as the Father of the Indian space program;
He was a great institution builder and established or helped to establish a large number of institutions 
in diverse fields.
He was instrumental in establishing the Physical Research Laboratory (PRL) in Ahmedabad : 
after returning from Cambridge to an independent India in 1947, he persuaded charitable trusts controlled by his family and friends to endow a research institution near home in Ahmedabad. Thus, Vikram Sarabhai founded the Physical Research Laboratory (PRL) in Ahmedabad on November 11, 1947. He was only 28 at that time. Sarabhai was a creator and cultivator of institutions and PRL was the first step in that direction. Vikram Sarabhai served of PRL from 1966-1971.
He was also Chairman of the Atomic Energy Commission.
He along with other Ahmedabad-based industrialists played a major role in the creation 
of the Indian Institute of Management, Ahmedabad.'''

In [75]:
stemmer = PorterStemmer()
docs = sent_tokenize(corpus)
print(type(docs),len(docs))
print(docs)

<class 'list'> 8
['Dr.Sarabhai is considered as the Father of the Indian space program;\nHe was a great institution builder and established or helped to establish a large number of institutions \nin diverse fields.', 'He was instrumental in establishing the Physical Research Laboratory (PRL) in Ahmedabad : \nafter returning from Cambridge to an independent India in 1947, he persuaded charitable trusts controlled by his family and friends to endow a research institution near home in Ahmedabad.', 'Thus, Vikram Sarabhai founded the Physical Research Laboratory (PRL) in Ahmedabad on November 11, 1947.', 'He was only 28 at that time.', 'Sarabhai was a creator and cultivator of institutions and PRL was the first step in that direction.', 'Vikram Sarabhai served of PRL from 1966-1971.', 'He was also Chairman of the Atomic Energy Commission.', 'He along with other Ahmedabad-based industrialists played a major role in the creation \nof the Indian Institute of Management, Ahmedabad.']


In [76]:
for var in range(len(docs)):
    words = word_tokenize(docs[var])
    print(words)

['Dr.Sarabhai', 'is', 'considered', 'as', 'the', 'Father', 'of', 'the', 'Indian', 'space', 'program', ';', 'He', 'was', 'a', 'great', 'institution', 'builder', 'and', 'established', 'or', 'helped', 'to', 'establish', 'a', 'large', 'number', 'of', 'institutions', 'in', 'diverse', 'fields', '.']
['He', 'was', 'instrumental', 'in', 'establishing', 'the', 'Physical', 'Research', 'Laboratory', '(', 'PRL', ')', 'in', 'Ahmedabad', ':', 'after', 'returning', 'from', 'Cambridge', 'to', 'an', 'independent', 'India', 'in', '1947', ',', 'he', 'persuaded', 'charitable', 'trusts', 'controlled', 'by', 'his', 'family', 'and', 'friends', 'to', 'endow', 'a', 'research', 'institution', 'near', 'home', 'in', 'Ahmedabad', '.']
['Thus', ',', 'Vikram', 'Sarabhai', 'founded', 'the', 'Physical', 'Research', 'Laboratory', '(', 'PRL', ')', 'in', 'Ahmedabad', 'on', 'November', '11', ',', '1947', '.']
['He', 'was', 'only', '28', 'at', 'that', 'time', '.']
['Sarabhai', 'was', 'a', 'creator', 'and', 'cultivator', 'o

In [79]:
for var in range(len(docs)):
    words = word_tokenize(docs[var])
    for word in words:
        if word.lower() not in stopwords.words('english'):
            print(word.lower())

dr.sarabhai
considered
father
indian
space
program
;
great
institution
builder
established
helped
establish
large
number
institutions
diverse
fields
.
instrumental
establishing
physical
research
laboratory
(
prl
)
ahmedabad
:
returning
cambridge
independent
india
1947
,
persuaded
charitable
trusts
controlled
family
friends
endow
research
institution
near
home
ahmedabad
.
thus
,
vikram
sarabhai
founded
physical
research
laboratory
(
prl
)
ahmedabad
november
11
,
1947
.
28
time
.
sarabhai
creator
cultivator
institutions
prl
first
step
direction
.
vikram
sarabhai
served
prl
1966-1971
.
also
chairman
atomic
energy
commission
.
along
ahmedabad-based
industrialists
played
major
role
creation
indian
institute
management
,
ahmedabad
.


In [80]:
for var in range(len(docs)):
    words = word_tokenize(docs[var])
    for word in words:
        if word.lower() not in set(stopwords.words('english')):
            print(word.lower())

dr.sarabhai
considered
father
indian
space
program
;
great
institution
builder
established
helped
establish
large
number
institutions
diverse
fields
.
instrumental
establishing
physical
research
laboratory
(
prl
)
ahmedabad
:
returning
cambridge
independent
india
1947
,
persuaded
charitable
trusts
controlled
family
friends
endow
research
institution
near
home
ahmedabad
.
thus
,
vikram
sarabhai
founded
physical
research
laboratory
(
prl
)
ahmedabad
november
11
,
1947
.
28
time
.
sarabhai
creator
cultivator
institutions
prl
first
step
direction
.
vikram
sarabhai
served
prl
1966-1971
.
also
chairman
atomic
energy
commission
.
along
ahmedabad-based
industrialists
played
major
role
creation
indian
institute
management
,
ahmedabad
.


In [82]:
L=['data1','data2','data1','data2','DATA1','Dr.sarabhai','sarabhai']
set(L) # omit duplicates 

{'DATA1', 'Dr.sarabhai', 'data1', 'data2', 'sarabhai'}

In [84]:
L=['D1','D2']
' '.join(L)

'D1 D2'

In [85]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

stemmer = PorterStemmer()
docs = nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words = nltk.word_tokenize(docs[var])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    docs[var] = " ".join(words)

docs

['dr.sarabhai consid father indian space program ; he great institut builder establish help establish larg number institut divers field .',
 'he instrument establish physic research laboratori ( prl ) ahmedabad : return cambridg independ india 1947 , persuad charit trust control famili friend endow research institut near home ahmedabad .',
 'thu , vikram sarabhai found physic research laboratori ( prl ) ahmedabad novemb 11 , 1947 .',
 'he 28 time .',
 'sarabhai creator cultiv institut prl first step direct .',
 'vikram sarabhai serv prl 1966-1971 .',
 'he also chairman atom energi commiss .',
 'he along ahmedabad-bas industrialist play major role creation indian institut manag , ahmedabad .']

In [ ]:
## use lemmatization

In [86]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemmatizer = WordNetLemmatizer()
docs = nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words = nltk.word_tokenize(docs[var])
    words = [lemmatizer.lemmatize(word,pos='v') for word in words 
             if word not in set(stopwords.words('english'))]
    docs[var] = " ".join(words)

docs

['Dr.Sarabhai consider Father Indian space program ; He great institution builder establish help establish large number institutions diverse field .',
 'He instrumental establish Physical Research Laboratory ( PRL ) Ahmedabad : return Cambridge independent India 1947 , persuade charitable trust control family friends endow research institution near home Ahmedabad .',
 'Thus , Vikram Sarabhai found Physical Research Laboratory ( PRL ) Ahmedabad November 11 , 1947 .',
 'He 28 time .',
 'Sarabhai creator cultivator institutions PRL first step direction .',
 'Vikram Sarabhai serve PRL 1966-1971 .',
 'He also Chairman Atomic Energy Commission .',
 'He along Ahmedabad-based industrialists play major role creation Indian Institute Management , Ahmedabad .']

In [ ]:
ngrams
========
An n-gram is contiguous sequence of n items from a given corpus/speech.

food good bad <== after apply lemmatization and stop words
-------------
 |-> [food good bad]  =>  n = 3 <= no.of unique words

One-Hot encoding
-----------------
food             =>  1 0 0
good             =>  0 1 0
bad              =>  0 0 1 

1. Predict next words
This is ...... <=== next word could .. 

2. Text similartiy 

food             =>  1 0 0
good             =>  0 1 0
bad              =>  0 0 1 
------------------------------ n = 1 


food good bad
n=2
food good  1 0
good bad   0 1

n=3
food good bad => 1
                 0

In [87]:
from nltk.util import ngrams

In [90]:
data = "likes read nlp applications"
tokens = word_tokenize(data)
ngrams(tokens,1)

<generator object ngrams at 0x000002993C5C9840>

In [91]:
list(ngrams(tokens,1))

[('likes',), ('read',), ('nlp',), ('applications',)]

In [92]:
list(ngrams(tokens,2))

[('likes', 'read'), ('read', 'nlp'), ('nlp', 'applications')]

In [93]:
list(ngrams(tokens,3))

[('likes', 'read', 'nlp'), ('read', 'nlp', 'applications')]

In [94]:
list(ngrams(tokens,4))

[('likes', 'read', 'nlp', 'applications')]

In [95]:
list(ngrams(tokens,5))

[]

In [99]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data = ['he','widely','regrad','father','indian','space','program']

data = np.array(data).reshape(-1,1) # 2D

encoder_obj = OneHotEncoder(sparse_output=False)
one_hot = encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot)

[array(['father', 'he', 'indian', 'program', 'regrad', 'space', 'widely'],
      dtype='<U7')]

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [100]:
L=[10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [101]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr+100

array([110, 120, 130, 140, 150])

In [102]:
arr.ndim

1

In [104]:
arr = np.array([[10,20,30,40,50]])
arr.ndim

2

In [105]:
arr

array([[10, 20, 30, 40, 50]])

In [108]:
arr=np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [107]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [110]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [111]:
arr.dtype

dtype('int64')

In [ ]:
Bag of Words (BOW) 
------------------
 ->word frequency 
 ->not word order / grammar 

Bag ->contains list of items

doc1 => i like nlp
doc2 => i like machine learning
|
Step1 : Collect all unique words => [ 'i','like','nlp','machine','learning']
Step2: Create vector for each sentence 
+--------------------------+-----+------+-----+---------+----------+
| sentence                 |  i  | like | nlp | machine | learning |
|i like nlp                |  1      1     1      0           0
|i like machine learning   |  1      1     0      1           1
+------------------------------------------------------------------+

S1 = [ 1,1,1,0,0]
S2 = [ 1,1,0,1,1]
|
similariry

In [116]:
from sklearn.feature_extraction.text import CountVectorizer

# sample docs
text = ['i like nlp','i like machine learning']

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(text)
print('vocs:',vectorizer.get_feature_names_out())
print('')
print('BOW:',X.toarray())

vocs: ['learning' 'like' 'machine' 'nlp']

BOW: [[0 1 0 1]
 [1 1 1 0]]


In [ ]:
### Practice time - 5-10 mts
https://github.com/pakarthikstudent/OU_GenAI_Oct25-/blob/main/DAY1/GenAI-LLM-1.ipynb

In [ ]:
TF-IDF
            Total terms in documents
TF =       ---------------------------------------
              Number of times term appears in document

DF = log(TF)

TF - IDF score
TF X IDF
weigheted  0-1

Downweight = 0
upweight = 1

In [117]:
from sklearn.feature_extraction.text import TfidfVectorizer

# sample docs
text = ['i like nlp','i like machine learning']

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(text)
print('vocs:',vectorizer.get_feature_names_out())
print('')
print('TF-IDF:',X.toarray())

vocs: ['learning' 'like' 'machine' 'nlp']

TF-IDF: [[0.         0.57973867 0.         0.81480247]
 [0.6316672  0.44943642 0.6316672  0.        ]]


In [ ]:
#######################################

In [ ]:
BOW  Vs                    TF-IDF
---
rawcounts               weighted
text classification     search engines

TF-IDF  Vs                       word2vec
-------                         =========
statistical                    neuarl network
frequence based(pattern)      semantic (pattern - meaning-based => hello hi )
relationship between words    relationship between words applied based semantic 
not applied               


In [ ]:
!pip install gensim

In [119]:
from gensim.models import Word2Vec

sentences = [ ["i","like","ai"],["ai","is","the","next"],["i","like","machine","learning"]]

#help(Word2Vec)
model = Word2Vec(sentences,vector_size=10,window=2,min_count=1,sg=1)
model.wv["ai"]

array([-0.00536227,  0.00236431,  0.0510335 ,  0.09009273, -0.0930295 ,
       -0.07116809,  0.06458873,  0.08972988, -0.05015428, -0.03763372],
      dtype=float32)

In [120]:
model.wv.most_similar("ai")

[('like', 0.5436005592346191),
 ('i', 0.3004249036312103),
 ('learning', 0.10494351387023926),
 ('is', -0.1311161071062088),
 ('the', -0.1897382140159607),
 ('machine', -0.22418656945228577),
 ('next', -0.2726020812988281)]

In [ ]:
Transformer
============
input embedding - each word into dense vectors
positional encoding 
encoder and decoder 
attention mechanism 
Q K V //parameters 
Query
Key
Value

Input ---> [ Transformer ] --->output
               |
Input ---> [ Encoder and Decoder ] --->output
              ..         ...


Input ---> [ FeedForwardNN ] --->output
              |
             Self-Attention

InputTokens ->Embeddings + Positional Encoding
                |
                Encoder layers (N times)
                |
                Decoder layers (N times )
                |
                output probabilities (next word / translation)

In [122]:
from transformers import AutoTokenizer 
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased") # uncase -> box Box both are same
text = "i like learning ai"                                    # used subword-based method
tokens = tokenizer.tokenize(text)
token_ids = tokenizer.encode(text)

print("token:",tokens)
print("token id:",token_ids)

token: ['i', 'like', 'learning', 'ai']
token id: [101, 1045, 2066, 4083, 9932, 102]


In [123]:
decoded = tokenizer.decode(token_ids)
print(decoded)

[CLS] i like learning ai [SEP]


In [ ]:
Tokenization ->Transformer 

Step 1: Tokenization
        Token=word,subwords,sentence,character 

Step 2: text processing
        BOW;TF-IDF
Step 3: WordEmbedding (DL)
         Word2Vec/FastText
        word sematic 
Step 4: Neural Network
Step 5: Transformer
            |->encoder 
            |->decoder
            |->self-attention - relationship between all the words
"hello" ->[100s vectors]

In [ ]:
Embedding Model
-----------------
1. Output(result) -> vector ->[1,2,3..N]
2. Each word(token) ->represent numerically
3. Usecases: Semantic search,clustering,similarity search
4. we won't use any prompting 

Large Language Model
=======================
1. Output(result) ->Text
2. Usecases: chat,text generation,summarization
3. prompt techniques are applied

In [ ]:
personA  - 100books about list of birds <== Q1: 
Vs
personB  - 50books about list of birds   <== Q1:

person - model
books - vectors 
Q1: user prompts

In [ ]:
###############  End of the day1  #####################